"""
core/threat_classifier.py – Attack classification layer.

Uses a Random Forest classifier trained on labelled synthetic network
metrics to identify the type of active threat.
"""

from __future__ import annotations

from typing import Dict, List

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler

import config
from core.environment import NetworkEnvironment, NetworkMetrics
from core.threat_simulator import ThreatSimulator


class ThreatClassifier:
    """
    Multi-class classifier that maps a :class:`NetworkMetrics` snapshot
    to one of the five attack categories defined in :data:`config.ATTACK_TYPES`.

    The model is a :class:`~sklearn.ensemble.RandomForestClassifier`
    trained on synthetic data generated by :class:`ThreatSimulator`.

    Parameters
    ----------
    seed : int | None
        Optional random seed for reproducibility.
    """

    def __init__(self, seed: int | None = config.RF_RANDOM_STATE) -> None:
        self._scaler = StandardScaler()
        self._encoder = LabelEncoder()
        self._model = RandomForestClassifier(
            n_estimators=config.RF_N_ESTIMATORS,
            random_state=seed,
            n_jobs=-1,
        )
        self._fitted = False
        self._seed = seed

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------

    def fit(
        self,
        n_samples: int = config.TRAINING_SAMPLES,
        env: NetworkEnvironment | None = None,
    ) -> "ThreatClassifier":
        """
        Generate *n_samples* synthetic labelled samples (balanced across
        attack types) and train the classifier.

        Parameters
        ----------
        n_samples : int
            Total number of training samples (split evenly per class).
        env : NetworkEnvironment | None
            Underlying environment; a fresh one is created if omitted.

        Returns
        -------
        ThreatClassifier
            Self (for chaining).
        """
        if env is None:
            env = NetworkEnvironment(seed=self._seed)

        simulator = ThreatSimulator(env, seed=self._seed)
        samples_per_class = max(1, n_samples // len(config.ATTACK_TYPES))

        X: List[List[float]] = []
        y: List[str] = []

        for attack_type in config.ATTACK_TYPES:
            for _ in range(samples_per_class):
                metrics = simulator.inject(attack_type)
                X.append(metrics.to_feature_vector())
                y.append(attack_type)

        X_arr = np.array(X)
        y_arr = np.array(y)

        X_scaled = self._scaler.fit_transform(X_arr)
        y_encoded = self._encoder.fit_transform(y_arr)

        self._model.fit(X_scaled, y_encoded)
        self._fitted = True
        return self

    # ------------------------------------------------------------------
    # Inference
    # ------------------------------------------------------------------

    def predict(self, metrics: NetworkMetrics) -> str:
        """
        Classify *metrics* into one of the attack categories.

        Parameters
        ----------
        metrics : NetworkMetrics

        Returns
        -------
        str
            Attack type label (e.g. ``"DDoS"``, ``"Normal"``).
        """
        self._require_fitted()
        X = np.array([metrics.to_feature_vector()])
        X_scaled = self._scaler.transform(X)
        encoded = self._model.predict(X_scaled)
        label: str = str(self._encoder.inverse_transform(encoded)[0])
        return label

    def predict_proba(self, metrics: NetworkMetrics) -> Dict[str, float]:
        """
        Return class probabilities for *metrics*.

        Parameters
        ----------
        metrics : NetworkMetrics

        Returns
        -------
        dict[str, float]
            Mapping from attack type to probability.
        """
        self._require_fitted()
        X = np.array([metrics.to_feature_vector()])
        X_scaled = self._scaler.transform(X)
        proba = self._model.predict_proba(X_scaled)[0]
        classes: List[str] = list(self._encoder.inverse_transform(self._model.classes_))
        return {cls: float(p) for cls, p in zip(classes, proba)}

    def feature_importances(self) -> Dict[str, float]:
        """
        Return feature importance scores from the trained Random Forest.

        Returns
        -------
        dict[str, float]
        """
        self._require_fitted()
        feat_names = NetworkMetrics(0, 0, 0, 0, 0, 0, 0).feature_names
        importances = self._model.feature_importances_
        return dict(zip(feat_names, importances.tolist()))

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _require_fitted(self) -> None:
        if not self._fitted:
            raise RuntimeError(
                "ThreatClassifier has not been trained. Call fit() first."
            )

    @property
    def is_fitted(self) -> bool:
        """Return ``True`` if the model has been trained."""
        return self._fitted
